{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodered-template-fila-email2.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nodered-template-fila-email2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nodered-template-fila-email.selectorLabels" . | nindent 4 }}
{{- end }}
